# -*- coding: utf-8 -*-
"""Career_Counselor_TinyLlama_Finetune (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ui6WzsZmlouumh8qR5ND-QmO_6ltZNYA

#  Career Counselor Bot — TinyLlama 1.1B

## ✅ Step 1 — Check GPU
"""

!nvidia-smi
import torch
print(f'\nGPU Available: {torch.cuda.is_available()}')
print(f'GPU: {torch.cuda.get_device_name(0)}')
print(f'Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

"""## ✅ Step 2 — Install Libraries"""

!pip install -q transformers datasets peft trl accelerate bitsandbytes
print('✅ Done!')

"""## ✅ Step 3 — Upload Dataset"""

from google.colab import files
print('📂 Upload your career_qa_dataset.json')
uploaded = files.upload()
print('✅ Uploaded!')

"""## ✅ Step 4 — Load and Format Dataset"""

import json
from datasets import Dataset

with open('career_qa_dataset.json', 'r') as f:
    raw_data = json.load(f)

system_prompt = 'You are an expert career counselor specializing in helping students in India choose the right career path. Always be encouraging, specific, and data-driven in your responses.'

# TinyLlama chat format
def format_example(item):
    text = (
        f"<|system|>\n{system_prompt}</s>\n"
        f"<|user|>\n{item['question']}</s>\n"
        f"<|assistant|>\n{item['answer']}</s>"
    )
    return {'text': text}

formatted = [format_example(item) for item in raw_data]
dataset = Dataset.from_list(formatted)

print(f'✅ Loaded {len(dataset)} examples!')
print('\n--- Sample ---')
print(dataset[0]['text'][:400])

"""## ✅ Step 5 — Load TinyLlama Model

"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'
print('⏳ Loading TinyLlama...')

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_compute_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'right'

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map='auto'
)
model.config.use_cache = False

print('✅ TinyLlama loaded!')
print(f'Memory used: {torch.cuda.memory_allocated()/1e9:.2f} GB')

"""## ✅ Step 6 — Set Up LoRA"""

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=['q_proj', 'v_proj'],
    lora_dropout=0.05,
    bias='none',
    task_type='CAUSAL_LM'
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
print('\n✅ LoRA ready!')

"""## ✅ Step 7 — Train!"""

from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir='./tinyllama-career-counselor',
    num_train_epochs=3,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    fp16=False,
    bf16=False,
    logging_steps=10,
    save_steps=50,
    dataset_text_field='text',
    warmup_steps=10,
    lr_scheduler_type='cosine',
    optim='paged_adamw_8bit',
    report_to='none'
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    args=training_args
)

print('🚀 Training started!')
trainer.train()
print('🎉 Training complete!')

"""## ✅ Step 8 — Save"""

trainer.save_model('./tinyllama-career-counselor')
tokenizer.save_pretrained('./tinyllama-career-counselor')
print('✅ Saved!')

"""## ✅ Step 9 — Test Your Bot 🎓"""

from transformers import pipeline

def ask_bot(question):
    prompt = (
        f"<|system|>\nYou are an expert career counselor for Indian students.</s>\n"
        f"<|user|>\n{question}</s>\n"
        f"<|assistant|>\n"
    )
    pipe = pipeline('text-generation', model=model, tokenizer=tokenizer, max_new_tokens=250)
    result = pipe(prompt)[0]['generated_text']
    return result.split('<|assistant|>')[-1].strip()

questions = [
    'I am a Science PCM student. What career should I choose?',
    'I love coding. Which engineering branch is best?',
    'What is the scope of Data Science in India?'
]

for q in questions:
    print(f'\n👤 {q}')
    print(f'🤖 {ask_bot(q)}')
    print('-' * 60)

"""## ✅ Step 10 — Download Model"""

import shutil
from google.colab import files
shutil.make_archive('tinyllama-career-counselor', 'zip', './tinyllama-career-counselor')
files.download('tinyllama-career-counselor.zip')
print('✅ Downloaded! 🎉')